inherit_from: .rubocop_todo.yml

AllCops:
    TargetRubyVersion: 3.0
    Exclude:
        - lib/prometheus/api_client/version.rb
    NewCops: disable
    SuggestExtensions: false

Layout/HashAlignment:
    EnforcedHashRocketStyle: table

Style/TrailingCommaInArguments:
    EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
    EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
    EnforcedStyleForMultiline: comma

Metrics/AbcSize:
    Max: 18

Metrics/MethodLength:
    Max: 23

Metrics/BlockLength:
    Exclude:
        - 'spec/**/*.rb'

Layout/LineLength:
    Exclude:
        - 'spec/**/*.rb'
