sudo: false
language: ruby
# Needed for rainbow 2.2.1 / rubygems issues.
before_install:
  - |
    if [[ "$(ruby -e 'puts RUBY_VERSION')" != 1.* ]]; then gem update --system; fi
rvm:
  - 3.0.5
  - 3.1.3
  - 3.2.1
  - jruby-9.4.1.0
