---
http_interactions:
- request:
    method: get
    uri: https://prometheus.example.com/api/v1/query?query=sum(container_cpu_usage_seconds_total%7Bjob=%22kubernetes-cadvisor%22,instance=%22example.com%22,id=%22/%22%7D)&time=2017-08-07T06:10:30.781Z
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Authorization:
      - Bearer topSecret
      User-Agent:
      - Faraday v0.12.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Length:
      - '63'
      Content-Type:
      - application/json
      Date:
      - Tue, 08 Aug 2017 08:27:23 GMT
      Set-Cookie:
      - bd337c9bdedd23361d6a22bfc4876b73=44e5e3f1c41ffda8509c6f9fbf8b9402; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"vector","result":[]}}'
    http_version: 
  recorded_at: Tue, 08 Aug 2017 08:27:23 GMT
- request:
    method: get
    uri: https://prometheus.example.com/api/v1/query_range?end=2017-08-07T06:14:30.781Z&query=sum(container_cpu_usage_seconds_total%7Bjob=%22kubernetes-cadvisor%22,instance=%22example.com%22,id=%22/%22%7D)&start=2017-08-07T06:10:30.781Z&step=120s
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Authorization:
      - Bearer topSecret
      User-Agent:
      - Faraday v0.12.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Length:
      - '63'
      Content-Type:
      - application/json
      Date:
      - Tue, 08 Aug 2017 08:27:23 GMT
      Set-Cookie:
      - bd337c9bdedd23361d6a22bfc4876b73=44e5e3f1c41ffda8509c6f9fbf8b9402; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"matrix","result":[]}}'
    http_version: 
  recorded_at: Tue, 08 Aug 2017 08:27:23 GMT
recorded_with: VCR 3.0.3
