---
http_interactions:
- request:
    method: get
    uri: https://prometheus.example.com/api/v1/label/job/values
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Authorization:
      - Bearer toSecret
      User-Agent:
      - Faraday v0.12.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Length:
      - '125'
      Content-Type:
      - application/json
      Date:
      - Tue, 08 Aug 2017 09:24:01 GMT
      Set-Cookie:
      - bd337c9bdedd23361d6a22bfc4876b73=44e5e3f1c41ffda8509c6f9fbf8b9402; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"status":"success","data":["kubernetes-apiservers","kubernetes-cadvisor","kubernetes-nodes","kubernetes-service-endpoints"]}'
    http_version: 
  recorded_at: Tue, 08 Aug 2017 09:24:01 GMT
- request:
    method: get
    uri: https://prometheus.example.com/api/v1/targets
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Authorization:
      - Bearer toSecret
      User-Agent:
      - Faraday v0.12.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Tue, 08 Aug 2017 09:24:01 GMT
      Transfer-Encoding:
      - chunked
      Set-Cookie:
      - bd337c9bdedd23361d6a22bfc4876b73=44e5e3f1c41ffda8509c6f9fbf8b9402; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"activeTargets":[{"discoveredLabels":{"__address__":"10.35.19.248:8443","__meta_kubernetes_endpoint_port_name":"https","__meta_kubernetes_endpoint_port_protocol":"TCP","__meta_kubernetes_endpoint_ready":"true","__meta_kubernetes_endpoints_name":"kubernetes","__meta_kubernetes_namespace":"default","__meta_kubernetes_service_label_component":"apiserver","__meta_kubernetes_service_label_provider":"kubernetes","__meta_kubernetes_service_name":"kubernetes","__metrics_path__":"/metrics","__scheme__":"https","job":"kubernetes-apiservers"},"labels":{"instance":"10.35.19.248:8443","job":"kubernetes-apiservers"},"scrapeUrl":"https://10.35.19.248:8443/metrics","lastError":"","lastScrape":"2017-08-08T09:23:40.919424567Z","health":"up"},{"discoveredLabels":{"__address__":"10.35.19.248:10250","__meta_kubernetes_node_address_Hostname":"yzamir-centos7-3.eng.lab.tlv.redhat.com","__meta_kubernetes_node_address_InternalIP":"10.35.19.248","__meta_kubernetes_node_annotation_volumes_kubernetes_io_controller_managed_attach_detach":"true","__meta_kubernetes_node_label_beta_kubernetes_io_arch":"amd64","__meta_kubernetes_node_label_beta_kubernetes_io_os":"linux","__meta_kubernetes_node_label_kubernetes_io_hostname":"yzamir-centos7-3.eng.lab.tlv.redhat.com","__meta_kubernetes_node_label_region":"infra","__meta_kubernetes_node_label_zone":"default","__meta_kubernetes_node_name":"yzamir-centos7-3.eng.lab.tlv.redhat.com","__metrics_path__":"/metrics","__scheme__":"https","instance":"yzamir-centos7-3.eng.lab.tlv.redhat.com","job":"kubernetes-nodes"},"labels":{"beta_kubernetes_io_arch":"amd64","beta_kubernetes_io_os":"linux","instance":"yzamir-centos7-3.eng.lab.tlv.redhat.com","job":"kubernetes-nodes","kubernetes_io_hostname":"yzamir-centos7-3.eng.lab.tlv.redhat.com","region":"infra","zone":"default"},"scrapeUrl":"https://10.35.19.248:10250/metrics","lastError":"","lastScrape":"2017-08-08T09:23:41.832027061Z","health":"up"},{"discoveredLabels":{"__address__":"10.35.19.248:10250","__meta_kubernetes_node_address_Hostname":"yzamir-centos7-3.eng.lab.tlv.redhat.com","__meta_kubernetes_node_address_InternalIP":"10.35.19.248","__meta_kubernetes_node_annotation_volumes_kubernetes_io_controller_managed_attach_detach":"true","__meta_kubernetes_node_label_beta_kubernetes_io_arch":"amd64","__meta_kubernetes_node_label_beta_kubernetes_io_os":"linux","__meta_kubernetes_node_label_kubernetes_io_hostname":"yzamir-centos7-3.eng.lab.tlv.redhat.com","__meta_kubernetes_node_label_region":"infra","__meta_kubernetes_node_label_zone":"default","__meta_kubernetes_node_name":"yzamir-centos7-3.eng.lab.tlv.redhat.com","__metrics_path__":"/metrics/cadvisor","__scheme__":"https","instance":"yzamir-centos7-3.eng.lab.tlv.redhat.com","job":"kubernetes-cadvisor"},"labels":{"beta_kubernetes_io_arch":"amd64","beta_kubernetes_io_os":"linux","instance":"yzamir-centos7-3.eng.lab.tlv.redhat.com","job":"kubernetes-cadvisor","kubernetes_io_hostname":"yzamir-centos7-3.eng.lab.tlv.redhat.com","region":"infra","zone":"default"},"scrapeUrl":"https://10.35.19.248:10250/metrics/cadvisor","lastError":"","lastScrape":"2017-08-08T09:24:00.587199854Z","health":"up"},{"discoveredLabels":{"__address__":"10.35.19.248:443","__meta_kubernetes_endpoint_port_name":"443-tcp","__meta_kubernetes_endpoint_port_protocol":"TCP","__meta_kubernetes_endpoint_ready":"true","__meta_kubernetes_endpoints_name":"router","__meta_kubernetes_namespace":"default","__meta_kubernetes_pod_annotation_kubernetes_io_created_by":"{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicationController\",\"namespace\":\"default\",\"name\":\"router-1\",\"uid\":\"872bac6a-7299-11e7-8221-001a4a2314d7\",\"apiVersion\":\"v1\",\"resourceVersion\":\"1206\"}}\n","__meta_kubernetes_pod_annotation_openshift_io_deployment_config_latest_version":"1","__meta_kubernetes_pod_annotation_openshift_io_deployment_config_name":"router","__meta_kubernetes_pod_annotation_openshift_io_deployment_name":"router-1","__meta_kubernetes_pod_annotation_openshift_io_scc":"hostnetwork","__meta_kubernetes_pod_container_name":"router","__meta_kubernetes_pod_container_port_name":"","__meta_kubernetes_pod_container_port_number":"443","__meta_kubernetes_pod_container_port_protocol":"TCP","__meta_kubernetes_pod_host_ip":"10.35.19.248","__meta_kubernetes_pod_ip":"10.35.19.248","__meta_kubernetes_pod_label_deployment":"router-1","__meta_kubernetes_pod_label_deploymentconfig":"router","__meta_kubernetes_pod_label_router":"router","__meta_kubernetes_pod_name":"router-1-ct5bh","__meta_kubernetes_pod_node_name":"yzamir-centos7-3.eng.lab.tlv.redhat.com","__meta_kubernetes_pod_ready":"true","__meta_kubernetes_service_annotation_prometheus_io_port":"1936","__meta_kubernetes_service_annotation_prometheus_io_scrape":"true","__meta_kubernetes_service_annotation_prometheus_openshift_io_password":"5fCg06IOyO","__meta_kubernetes_service_annotation_prometheus_openshift_io_username":"admin","__meta_kubernetes_service_label_router":"router","__meta_kubernetes_service_name":"router","__metrics_path__":"/metrics","__scheme__":"http","job":"kubernetes-service-endpoints"},"labels":{"instance":"10.35.19.248:1936","job":"kubernetes-service-endpoints","kubernetes_name":"router","kubernetes_namespace":"default","router":"router"},"scrapeUrl":"http://10.35.19.248:1936/metrics","lastError":"server
        returned HTTP status 403 Forbidden","lastScrape":"2017-08-08T09:23:29.647620005Z","health":"down"},{"discoveredLabels":{"__address__":"10.128.0.7:8443","__meta_kubernetes_endpoint_port_name":"prometheus","__meta_kubernetes_endpoint_port_protocol":"TCP","__meta_kubernetes_endpoint_ready":"true","__meta_kubernetes_endpoints_name":"prometheus","__meta_kubernetes_namespace":"kube-system","__meta_kubernetes_pod_annotation_kubernetes_io_created_by":"{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicaSet\",\"namespace\":\"kube-system\",\"name\":\"prometheus-1552260379\",\"uid\":\"dada58d9-72aa-11e7-8221-001a4a2314d7\",\"apiVersion\":\"extensions\",\"resourceVersion\":\"3185\"}}\n","__meta_kubernetes_pod_annotation_openshift_io_scc":"restricted","__meta_kubernetes_pod_container_name":"oauth-proxy","__meta_kubernetes_pod_container_port_name":"web","__meta_kubernetes_pod_container_port_number":"8443","__meta_kubernetes_pod_container_port_protocol":"TCP","__meta_kubernetes_pod_host_ip":"10.35.19.248","__meta_kubernetes_pod_ip":"10.128.0.7","__meta_kubernetes_pod_label_app":"prometheus","__meta_kubernetes_pod_label_pod_template_hash":"1552260379","__meta_kubernetes_pod_name":"prometheus-1552260379-fq410","__meta_kubernetes_pod_node_name":"yzamir-centos7-3.eng.lab.tlv.redhat.com","__meta_kubernetes_pod_ready":"true","__meta_kubernetes_service_annotation_openshift_io_generated_by":"OpenShiftNewApp","__meta_kubernetes_service_annotation_prometheus_io_scheme":"https","__meta_kubernetes_service_annotation_prometheus_io_scrape":"true","__meta_kubernetes_service_annotation_service_alpha_openshift_io_serving_cert_secret_name":"prometheus-tls","__meta_kubernetes_service_annotation_service_alpha_openshift_io_serving_cert_signed_by":"openshift-service-serving-signer@1501138614","__meta_kubernetes_service_label_name":"prometheus","__meta_kubernetes_service_name":"prometheus","__metrics_path__":"/metrics","__scheme__":"http","job":"kubernetes-service-endpoints"},"labels":{"instance":"10.128.0.7:8443","job":"kubernetes-service-endpoints","kubernetes_name":"prometheus","kubernetes_namespace":"kube-system","name":"prometheus"},"scrapeUrl":"https://10.128.0.7:8443/metrics","lastError":"","lastScrape":"2017-08-08T09:23:35.197491923Z","health":"up"}]}}'
    http_version: 
  recorded_at: Tue, 08 Aug 2017 09:24:01 GMT
recorded_with: VCR 3.0.3
